import { Equipped } from "features/game/types/bumpkin";
import { PolyTownNpcName } from "./nameTypes";

export const POLY_TOWN_NPC_WEARABLES: Record<PolyTownNpcName, Equipped> = {
  ned: {
    background: "Farm Background",
    body: "Dark Brown Farmer Potion",
    hair: "Explorer Hair",
    shoes: "Cupid Sandals",
    hat: "Boater Hat",
    tool: "Water Gun",
    pants: "Beach Trunks",
    shirt: "Hawaiian Shirt",
  },
  "poly bear": {
    background: "Farm Background",
    body: "Beige Farmer Potion",
    hair: "Buzz Cut",
    shoes: "Black Farmer Boots",
    tool: "Candy Cane",
    pants: "Farmer Pants",
    shirt: "Red Farmer Shirt",
    onesie: "Bear Onesie",
  },
  cluck: {
    background: "Farm Background",
    body: "Elf Potion",
    hat: "Straw Hat",
    hair: "Basic Hair",
    shoes: "Brown Boots",
    tool: "Farmer Pitchfork",
    pants: "Farmer Pants",
    shirt: "Red Farmer Shirt",
    onesie: "Corn Onesie",
  },
  oblivia: {
    background: "Cemetery Background",
    body: "Light Brown Farmer Potion",
    hair: "White Long Hair",
    hat: "Luna's Hat",
    dress: "Witching Wardrobe",
    tool: "Witch's Broom",
    shoes: "Brown Boots",
  },
  autumn: {
    background: "Farm Background",
    hair: "Ash Ponytail",
    body: "Beige Farmer Potion",
    shirt: "Yellow Farmer Shirt",
    pants: "Farmer Overalls",
    shoes: "Yellow Boots",
    tool: "Farmer Pitchfork",
    necklace: "Green Amulet",
    hat: "Farmer Hat",
  },
  garth: {
    background: "Farm Background",
    hair: "Basic Hair",
    body: "Dark Brown Farmer Potion",
    shirt: "Blue Farmer Shirt",
    pants: "Farmer Pants",
    shoes: "Yellow Boots",
    tool: "Farmer Pitchfork",
    necklace: "Green Amulet",
    hat: "Farmer Hat",
  },
  harlow: {
    background: "Farm Background",
    hair: "Teal Mohawk",
    body: "Beige Farmer Potion",
    shirt: "Skull Shirt",
    pants: "Fishing Pants",
    shoes: "Wellies",
    tool: "Merch Coffee Mug",
  },
  burt: {
    background: "Farm Background",
    hat: "Pirate Hat",
    hair: "Explorer Hair",
    body: "Beige Farmer Potion",
    shirt: "Pirate Leather Polo",
    pants: "Pirate Pants",
    shoes: "Peg Leg",
    tool: "Pirate Scimitar",
  },
  wynken: {
    background: "Farm Background",
    hat: "Feather Hat",
    hair: "Basic Hair",
    body: "Light Brown Farmer Potion",
    shirt: "Fancy Top",
    pants: "Fancy Pants",
    shoes: "Black Farmer Boots",
    tool: "Grave Diggers Shovel",
  },
};
